'use client'

import { ArrowRight, Flame } from 'lucide-react'
import { WebinarRegistrationForm } from '@/components/webinar-registration-form'

const tickerItems = ['DECIDE CON DATOS.', 'MENOS REPORTES. MÁS FOCO.', 'PRIORIZA TU CARTERA.', 'CLIENTES. PRODUCTOS. STOCK.', 'DE DATOS A DECISIONES.', 'LO QUE NO SE MIDE, NO SE MEJORA.', 'MENOS INFORMACIÓN. MÁS ACCIÓN.']

function Pill({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) {
  return <span className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-[10px] font-medium uppercase tracking-[0.16em] ${dark ? 'border-white/20 bg-white/5 text-white/70' : 'border-black/10 bg-white text-[#6f6963]'}`} style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{children}</span>
}

function BurnButton({ children, outline = false, href = '#registro' }: { children: React.ReactNode; outline?: boolean; href?: string }) {
  return <a href={href} className={`inline-flex min-h-12 items-center justify-center gap-3 rounded-full px-6 text-xs font-bold uppercase tracking-[0.12em] transition-transform hover:-translate-y-0.5 ${outline ? 'border border-[#0A0A0A] bg-transparent text-[#0A0A0A] hover:bg-[#0A0A0A] hover:text-white' : 'bg-[#FF4500] text-white hover:bg-[#0A0A0A]'}`} style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{children}<ArrowRight className="h-4 w-4" /></a>
}

function Header() {
  return <header className="px-4 pt-5 sm:px-8 sm:pt-8"><div className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-black/10 bg-[#F5F1EA]/90 px-5 py-3 backdrop-blur sm:px-7"><a href="#top" className="flex items-center gap-2 text-[#0A0A0A]"><Flame className="h-6 w-6 fill-[#FF4500] text-[#FF4500]" /><span className="text-lg font-black tracking-tight" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>THE BURN</span></a><div className="flex items-center gap-3"><span className="hidden text-[10px] font-medium uppercase tracking-widest text-[#6f6963] sm:inline" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>03 SEPT · 20:00</span><a href="#registro" className="rounded-full bg-[#0A0A0A] px-4 py-2.5 text-[10px] font-bold uppercase tracking-widest text-white" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Solicitar cupo <ArrowRight className="ml-1 inline h-3 w-3" /></a></div></div></header>
}

function Hero() {
  return <section id="top" className="px-4 pb-0 pt-20 text-center sm:px-8 sm:pt-28"><div className="mx-auto max-w-6xl"><Pill><span className="h-2 w-2 rounded-full bg-[#FF4500]" /> Taller ejecutivo online · 03 sept · 20:00 hrs</Pill><h1 className="mx-auto mt-8 max-w-5xl text-[clamp(4rem,13vw,10.5rem)] font-black uppercase leading-[0.78] tracking-[-0.055em] text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>De sell out a</h1><div className="mx-auto mt-4 max-w-4xl rounded-[2rem] bg-[#FF4500] px-5 py-5 text-[clamp(3.5rem,11vw,9rem)] font-black uppercase leading-[0.78] tracking-[-0.055em] text-white sm:px-10 sm:py-8" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Prioridades<br />comerciales</div><p className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-[#6f6963] sm:text-xl" style={{ fontFamily: 'var(--font-barlow)' }}>Cómo decidir dónde poner el foco entre clientes, productos, stock y equipo comercial.</p><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-[#938b82]" style={{ fontFamily: 'var(--font-barlow)' }}>Para dueños y gerentes de empresas que ya gestionan una operación comercial con múltiples clientes, productos y vendedores.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><BurnButton>Solicitar mi cupo</BurnButton><BurnButton outline href="#veremos">Ver qué veremos</BurnButton></div><p className="mt-5 text-[10px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>3 de septiembre · 20:00 hrs · Online · Hora Chile</p></div><Ticker /></section>
}

function Ticker() { return <div className="mt-24 -mx-4 flex overflow-hidden border-y border-black/10 bg-[#0A0A0A] py-4 sm:-mx-8"><div className="flex min-w-max animate-[marquee_38s_linear_infinite] items-center gap-8 text-[10px] font-bold uppercase tracking-[0.16em] text-white" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{[...tickerItems, ...tickerItems].map((item, index) => <span key={`${item}-${index}`} className={index % 3 === 1 ? 'text-[#FF4500]' : ''}>■ {item}</span>)}</div></div> }

function InsightSections() {
  return <>
    <section className="px-4 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-5xl"><Pill>¿Te pasa esto?</Pill><h2 className="mt-8 max-w-4xl text-[clamp(4rem,10vw,8.5rem)] font-black uppercase leading-[0.82] tracking-[-0.05em] text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Tienes datos.</h2><div className="mt-3 inline-block rounded-[1.5rem] bg-[#FF4500] px-5 py-4 text-[clamp(3.5rem,9vw,8rem)] font-black uppercase leading-[0.8] tracking-[-0.05em] text-white sm:px-8 sm:py-6" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Pero ¿dónde actúas?</div><p className="mt-8 max-w-2xl text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Cuando una empresa empieza a gestionar cientos de combinaciones entre clientes, productos, stock y vendedores, mirar el total de ventas deja de ser suficiente.</p></div></section>
    <section id="veremos" className="border-y border-black/10 px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><h2 className="max-w-4xl text-[clamp(3.5rem,8vw,7rem)] font-black uppercase leading-[0.82] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Este taller no es<br />para empezar a vender.</h2><div className="mt-5 max-w-4xl rounded-[1.5rem] bg-[#FF4500] px-5 py-5 text-[clamp(3rem,7vw,6rem)] font-black uppercase leading-[0.82] tracking-[-0.05em] text-white sm:px-8 sm:py-7" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Es para decidir<br />mejor dónde vender.</div><p className="mt-6 text-lg text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Pensado para empresas que ya tienen una operación comercial en marcha.</p><div className="mt-16 grid border-y border-black/10 sm:grid-cols-4">{['Cartera de clientes', 'Múltiples productos / SKU', 'Equipo comercial', 'Datos de venta / stock'].map((item, i) => <div key={item} className="border-b border-black/10 py-6 sm:border-b-0 sm:border-r sm:px-6 sm:last:border-r-0"><span className="text-5xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{String(i + 1).padStart(2, '0')}</span><p className="mt-3 text-sm font-bold uppercase leading-tight" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{item}</p></div>)}</div><p className="mt-10 max-w-2xl text-lg font-medium leading-relaxed text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow)' }}>Si tu desafío ya no es conseguir tus primeros clientes, sino gestionar mejor una operación que ha crecido, esta sesión está diseñada para ti.</p></div></section>
  </>
}

function Method() { return <section className="bg-[#0A0A0A] px-4 py-24 text-white sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill dark>Método The Burn</Pill><h2 className="mt-8 text-[clamp(4rem,11vw,9rem)] font-black uppercase leading-[0.78] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>De información<br />a acción.</h2><div className="mt-16 grid gap-7 sm:grid-cols-4 sm:gap-4">{[['DATO', 'Cliente disminuye compras durante 8 semanas.'], ['SEÑAL', 'Existe una caída sostenida.'], ['DECISIÓN', 'Se convierte en prioridad.'], ['ACCIÓN', 'Revisar categorías, stock y plan comercial.']].map(([title, text], i) => <div key={title} className="relative border-t border-white/20 pt-5 sm:border-t-0 sm:border-l sm:pl-5">{i > 0 && <span className="absolute -left-3 -top-4 hidden text-3xl text-[#FF4500] sm:block">→</span>}<p className="text-2xl font-black uppercase text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{title}</p><p className="mt-3 text-sm leading-6 text-white/65" style={{ fontFamily: 'var(--font-barlow)' }}>{text}</p></div>)}</div><div className="mt-20"><p className="text-3xl font-black uppercase sm:text-5xl" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>No necesitas más dashboards.</p><div className="mt-3 inline-block rounded-2xl bg-[#FF4500] px-5 py-3 text-3xl font-black uppercase sm:text-5xl" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Necesitas saber qué hacer.</div></div></div></section> }

function Complexity() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>La operación real</Pill><h2 className="mt-8 max-w-4xl text-[clamp(3.5rem,8vw,7rem)] font-black uppercase leading-[0.82] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Cuando la operación<br />se vuelve compleja.</h2><div className="mt-14 grid gap-3 sm:grid-cols-4">{[['+150', 'Clientes'], ['+800', 'SKU'], ['Varios', 'Vendedores'], ['Miles', 'Registros']].map(([number, label]) => <div key={label} className="rounded-3xl border border-black/10 bg-white p-6"><p className="text-5xl font-black uppercase text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{number}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{label}</p></div>)}</div><div className="mt-16 grid items-center gap-8 lg:grid-cols-2"><div><p className="text-3xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Gerencia no necesita ver todo.</p><div className="mt-4 rounded-2xl bg-[#FF4500] px-5 py-4 text-3xl font-black uppercase text-white" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Necesita saber qué priorizar.</div></div><div className="rounded-3xl bg-[#0A0A0A] p-5 text-white"><div className="flex items-center justify-between border-b border-white/15 pb-4"><span className="text-xs uppercase tracking-widest text-white/60" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Panel comercial</span><span className="h-2 w-2 rounded-full bg-[#FF4500]" /></div><div className="mt-8 grid grid-cols-3 gap-3 text-center">{[['68%', 'Retención'], ['24', 'Prioridades'], ['$42M', 'Pipeline']].map(([n, l]) => <div key={l}><p className="text-2xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{n}</p><p className="mt-1 text-[9px] uppercase text-white/55" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{l}</p></div>)}</div><div className="mt-8 h-20 rounded-xl bg-white/5 p-3"><div className="flex h-full items-end gap-2">{[35, 50, 42, 68, 55, 80, 72].map((h, i) => <div key={i} className={`flex-1 rounded-t ${i === 5 ? 'bg-[#FF4500]' : 'bg-white/25'}`} style={{ height: `${h}%` }} />)}</div></div></div></div></div></section> }

function Audience() { const people = ['Dueños', 'Gerentes generales', 'Gerentes comerciales', 'Líderes de ventas']; return <section className="border-y border-black/10 px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>Para quien decide</Pill><h2 className="mt-8 max-w-4xl text-[clamp(3.5rem,8vw,7rem)] font-black uppercase leading-[0.82] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Esta sesión es<br />para quien decide.</h2><div className="mt-14 grid border-y border-black/10 sm:grid-cols-4">{people.map((person, i) => <div key={person} className="flex items-center gap-4 border-b border-black/10 py-5 sm:border-b-0 sm:border-r sm:px-5 sm:last:border-r-0"><span className="text-xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>0{i + 1}</span><span className="text-sm font-bold uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{person}</span></div>)}</div><p className="mt-10 max-w-3xl text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Especialmente relevante para empresas de distribución, importación, fabricación, representación de marcas, mayoristas y venta recurrente a empresas o canales.</p></div></section> }

function NotCourse() { return <section className="bg-[#0A0A0A] px-4 py-24 text-white sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><h2 className="text-[clamp(3.5rem,9vw,8rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>No es un curso<br />de Power BI.<br /><span className="text-white/35">No es una clase<br />de Excel.</span></h2><p className="mt-10 text-3xl font-black uppercase text-[#FF4500] sm:text-6xl" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Es gestión comercial.</p><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/65" style={{ fontFamily: 'var(--font-barlow)' }}>Una sesión ejecutiva para transformar información de clientes, productos, ventas y stock en prioridades concretas.</p></div></section> }

function BeforeAfter() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>En 60 minutos</Pill><h2 className="mt-8 text-[clamp(4rem,10vw,8.5rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Cambiamos<br />la pregunta.</h2><div className="mt-14 grid gap-px border border-black/10 bg-black/10 sm:grid-cols-2"><div className="bg-white p-8 sm:p-12"><p className="text-sm font-bold uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Antes</p><p className="mt-10 text-4xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Cómo vamos<br />en ventas?</p></div><div className="bg-[#FF4500] p-8 text-white sm:p-12"><p className="text-sm font-bold uppercase tracking-widest text-white/70" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Ahora</p><p className="mt-10 text-4xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Dónde debemos<br />actuar?</p></div></div><div className="mt-12 grid gap-5 sm:grid-cols-4">{[['Clientes', '¿Quién requiere atención?'], ['Productos', '¿Dónde existe potencial?'], ['Stock', '¿Dónde hay riesgo?'], ['Equipo', '¿Dónde ponemos el esfuerzo comercial?']].map(([a, b]) => <div key={a} className="border-t border-black/15 pt-4"><p className="font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{a}</p><p className="mt-2 text-sm text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>{b}</p></div>)}</div></div></section> }

export function WebinarLanding() { return <div className="overflow-hidden bg-[#F5F1EA] text-[#0A0A0A]"><Header /><main><Hero /><InsightSections /><NotCourse /><BeforeAfter /><Method /><Complexity /><Audience /><section id="registro" className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><div><Pill>03 sept · 20:00 hrs · online</Pill><h2 className="mt-8 text-[clamp(4rem,9vw,8rem)] font-black uppercase leading-[0.78] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Solicita<br />tu cupo.</h2><p className="mt-6 max-w-sm text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Queremos mantener esta sesión enfocada en empresas con una operación comercial activa.</p></div><WebinarRegistrationForm /></div></section><section className="px-4 pb-32 pt-12 text-center sm:px-8"><Pill>03 sept · 20:00 hrs · online</Pill><h2 className="mx-auto mt-8 max-w-5xl text-[clamp(4rem,12vw,10rem)] font-black uppercase leading-[0.78] tracking-[-0.055em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Tus datos<br /><span className="inline-block rounded-[1.5rem] bg-[#FF4500] px-4 py-3 text-white">ya existen.</span></h2><p className="mt-8 text-lg text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Taller Ejecutivo THE BURN · Hora Chile</p><div className="mt-8"><BurnButton>Solicitar mi cupo</BurnButton></div></section></main><a href="#registro" className="fixed bottom-4 left-4 right-4 z-40 flex min-h-12 items-center justify-center rounded-full bg-[#FF4500] px-6 text-xs font-bold uppercase tracking-widest text-white shadow-xl sm:hidden" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Solicitar cupo <ArrowRight className="ml-2 h-4 w-4" /></a></div> }
