'use client'

import { useState } from 'react'
import { ArrowRight, Check, Flame } from 'lucide-react'
import { WebinarRegistrationForm } from '@/components/webinar-registration-form'

const tickerItems = ['DECIDE CON DATOS.', 'MENOS REPORTES. MÁS FOCO.', 'PRIORIZA TU CARTERA.', 'DE DATOS A DECISIONES.']

function Pill({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) {
  return <span className={`inline-flex w-fit items-center gap-2 rounded-full border px-4 py-2 text-[10px] font-bold uppercase tracking-[0.16em] ${dark ? 'border-white/20 bg-white/5 text-white/70' : 'border-black/10 bg-white text-[#6f6963]'}`} style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{children}</span>
}

function CTA({ children = 'Reservar mi cupo', dark = false }: { children?: React.ReactNode; dark?: boolean }) {
  return <a href="#registro" className={`inline-flex min-h-12 items-center justify-center gap-3 rounded-full px-6 text-xs font-bold uppercase tracking-[0.12em] transition-transform hover:-translate-y-0.5 ${dark ? 'bg-[#FF4500] text-white hover:bg-white hover:text-[#0A0A0A]' : 'bg-[#FF4500] text-white hover:bg-[#0A0A0A]'}`} style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{children}<ArrowRight className="h-4 w-4" /></a>
}

function Logo() {
  return <a href="#top" className="flex items-center gap-2 text-[#0A0A0A]"><Flame className="h-6 w-6 fill-[#FF4500] text-[#FF4500]" /><span className="text-lg font-black tracking-tight" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>THE BURN</span></a>
}

function Header() {
  return <header className="px-4 pt-5 sm:px-8 sm:pt-8"><div className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-black/10 bg-[#F5F1EA]/95 px-5 py-3 backdrop-blur sm:px-7"><Logo /><div className="hidden items-center gap-4 sm:flex"><span className="text-[10px] font-bold uppercase tracking-widest text-[#6f6963]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>03 sept · 20:00 hrs</span><CTA>Reservar mi cupo</CTA></div></div></header>
}

function Ticker() {
  return <div className="mt-14 -mx-4 flex overflow-hidden border-y border-black/10 bg-[#0A0A0A] py-4 sm:-mx-8"><div className="flex min-w-max animate-[marquee_38s_linear_infinite] gap-8 text-[10px] font-bold uppercase tracking-[0.16em] text-white" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{[...tickerItems, ...tickerItems].map((item, index) => <span key={`${item}-${index}`} className={index % 3 === 1 ? 'text-[#FF4500]' : ''}>■ {item}</span>)}</div></div>
}

function Hero() {
  return <section id="top" className="px-4 pb-0 pt-14 sm:px-8 sm:pt-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><Logo /><Pill><span className="h-2 w-2 rounded-full bg-[#FF4500]" /> Taller ejecutivo · Online · Sin costo</Pill><h1 className="mt-7 max-w-3xl text-[clamp(3.75rem,8vw,7.5rem)] font-black uppercase leading-[0.8] tracking-[-0.055em] text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>De sell out a</h1><div className="mt-3 w-fit max-w-full border-b-[6px] border-[#FF4500] pb-3 text-[clamp(3.5rem,8vw,7.5rem)] font-black uppercase leading-[0.78] tracking-[-0.055em] text-[#0A0A0A] sm:pb-5" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Prioridades<br />comerciales</div><p className="mt-7 max-w-2xl text-lg leading-relaxed text-[#6f6963] sm:text-xl" style={{ fontFamily: 'var(--font-barlow)' }}>Cómo decidir dónde poner el foco entre clientes, productos, stock y equipo comercial.</p><p className="mt-4 max-w-xl text-sm leading-6 text-[#938b82]" style={{ fontFamily: 'var(--font-barlow)' }}>Para dueños y gerentes de empresas que ya gestionan múltiples clientes, productos y un equipo comercial.</p><div className="mt-7 grid grid-cols-2 gap-3 border-y border-black/10 py-5 sm:grid-cols-4"><div><strong className="block text-lg font-black" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>03 SEPT 2026</strong><span className="text-[9px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Fecha</span></div><div><strong className="block text-lg font-black" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>20:00 HRS</strong><span className="text-[9px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Hora Chile</span></div><div><strong className="block text-lg font-black" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>ONLINE</strong><span className="text-[9px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Modalidad</span></div><div><strong className="block text-lg font-black" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>45 MIN</strong><span className="text-[9px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Duración</span></div></div><ul className="mt-6 grid gap-3 text-sm text-[#0A0A0A] sm:grid-cols-3" style={{ fontFamily: 'var(--font-barlow)' }}>{['Detecta clientes que requieren atención', 'Identifica oportunidades por producto', 'Define dónde debe actuar tu equipo comercial'].map((item) => <li key={item} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#FF4500]" />{item}</li>)}</ul></div><div id="registro" className="scroll-mt-8"><div className="mb-4 lg:hidden"><CTA>Reservar mi cupo</CTA></div><WebinarRegistrationForm /></div></div><Ticker /></section>
}

function ForYou() {
  const conditions = ['Cartera de clientes', 'Múltiples productos', 'Equipo comercial', 'Datos de venta / stock']
  return <section className="border-y border-black/10 px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>Para tomar mejores decisiones</Pill><h2 className="mt-7 max-w-4xl text-[clamp(3.8rem,9vw,8rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Esta sesión<br />es para ti?</h2><div className="mt-12 grid border-y border-black/10 sm:grid-cols-4">{conditions.map((item, i) => <div key={item} className="border-b border-black/10 py-6 sm:border-b-0 sm:border-r sm:px-6 sm:last:border-r-0"><span className="text-5xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>0{i + 1}</span><p className="mt-3 text-sm font-bold uppercase leading-tight" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{item}</p></div>)}</div><p className="mt-9 max-w-3xl text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Si tu desafío ya no es conseguir tus primeros clientes, sino decidir mejor dentro de una operación comercial que ha crecido, esta sesión está diseñada para ti.</p><div className="mt-7"><CTA /></div></div></section>
}

function Questions() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><h2 className="max-w-5xl text-[clamp(4rem,10vw,9rem)] font-black uppercase leading-[0.78] tracking-[-0.055em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Tienes los datos.</h2><div className="mt-3 w-fit border-b-[6px] border-[#FF4500] pb-3 text-[clamp(3rem,8vw,7rem)] font-black uppercase leading-[0.8] tracking-[-0.055em] text-[#0A0A0A]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Pero dónde actúas?</div><div className="mt-14 grid gap-0 border-y border-black/10 sm:grid-cols-2">{['¿Qué clientes deberían comprar más?', '¿Qué productos están perdiendo tracción?', '¿Dónde existe riesgo de stock?', '¿Dónde debería concentrarse el equipo comercial?'].map((q, i) => <div key={q} className="border-b border-black/10 p-6 sm:border-r sm:last:border-b-0 sm:nth-[2n]:border-r-0"><span className="text-sm font-bold text-[#FF4500]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>0{i + 1}</span><p className="mt-3 text-2xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{q}</p></div>)}</div></div></section> }

function Takeaways() { return <section className="bg-[#0A0A0A] px-4 py-24 text-white sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill dark>En 45 minutos</Pill><h2 className="mt-7 max-w-5xl text-[clamp(4rem,10vw,9rem)] font-black uppercase leading-[0.78] tracking-[-0.055em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Lo que te<br />llevarás.</h2><div className="mt-14 grid gap-px bg-white/15 sm:grid-cols-3">{[['01', 'Priorizar clientes', 'Detectar qué cuentas requieren atención y dónde existe potencial.'], ['02', 'Priorizar productos', 'Identificar crecimiento, deterioro, rotación y oportunidad.'], ['03', 'Pasar a la acción', 'Transformar información en prioridades concretas para gerencia y vendedores.']].map(([n, title, text]) => <div key={n} className="bg-[#0A0A0A] p-7 sm:p-8"><span className="text-5xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{n}</span><h3 className="mt-5 text-3xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{title}</h3><p className="mt-4 leading-relaxed text-white/65" style={{ fontFamily: 'var(--font-barlow)' }}>{text}</p></div>)}</div><p className="mt-14 max-w-3xl text-2xl font-black uppercase sm:text-4xl" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>No aprenderás a construir dashboards. <span className="text-[#FF4500]">Aprenderás a decidir qué hacer con ellos.</span></p></div></section> }

function BeforeAfter() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>Antes / Después</Pill><h2 className="mt-7 text-[clamp(4rem,10vw,9rem)] font-black uppercase leading-[0.78] tracking-[-0.055em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Cambiamos<br />la pregunta.</h2><div className="mt-12 grid gap-px border border-black/10 bg-black/10 sm:grid-cols-2"><div className="bg-white p-8 sm:p-12"><p className="text-[10px] font-bold uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Antes</p><p className="mt-10 text-4xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Cómo vamos<br />en ventas?</p></div><div className="bg-[#FF4500] p-8 text-white sm:p-12"><p className="text-[10px] font-bold uppercase tracking-widest text-white/70" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Después</p><p className="mt-10 text-4xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>¿Dónde deberíamos<br />actuar esta semana?</p></div></div><div className="mt-10 grid gap-5 sm:grid-cols-4">{['Dato', 'Señal', 'Decisión', 'Acción'].map((item, i) => <div key={item} className="border-t border-black/15 pt-4"><span className="text-2xl font-black uppercase text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{item}</span>{i < 3 && <ArrowRight className="mt-3 h-4 w-4 text-[#938b82]" />}</div>)}</div></div></section> }

function Example() { return <section className="border-y border-black/10 px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>La operación real</Pill><h2 className="mt-7 max-w-5xl text-[clamp(3.8rem,8vw,7.5rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>No será<br />solo teoría.</h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Trabajaremos sobre un ejemplo de una operación comercial con múltiples clientes, productos, ventas y stock.</p><div className="mt-12 grid gap-3 sm:grid-cols-4">{[['+150', 'Clientes'], ['+800', 'SKU'], ['Varios', 'Vendedores'], ['Miles', 'Registros']].map(([number, label]) => <div key={label} className="rounded-3xl border border-black/10 bg-white p-6"><p className="text-5xl font-black" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{number}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{label}</p></div>)}</div><div className="mt-12 grid items-center gap-8 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-[#FF4500]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>El objetivo</p><p className="mt-4 max-w-lg text-3xl font-black uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Convertir miles de datos en una lista corta de prioridades comerciales.</p></div><div className="rounded-3xl bg-[#0A0A0A] p-5 text-white"><div className="flex justify-between border-b border-white/15 pb-4"><span className="text-[10px] uppercase tracking-widest text-white/60" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Panel comercial</span><span className="h-2 w-2 rounded-full bg-[#FF4500]" /></div><div className="mt-7 grid grid-cols-3 gap-3 text-center">{[['68%', 'Retención'], ['24', 'Prioridades'], ['$42M', 'Pipeline']].map(([number, label]) => <div key={label}><p className="text-2xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{number}</p><p className="mt-1 text-[9px] uppercase text-white/55" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>{label}</p></div>)}</div><div className="mt-7 space-y-2">{['Cliente 018 · revisar caída', 'SKU 442 · recuperar rotación', 'Vendedor 03 · priorizar cartera'].map((line) => <div key={line} className="border-l-2 border-[#FF4500] bg-white/5 px-3 py-2 text-xs text-white/75" style={{ fontFamily: 'var(--font-barlow)' }}>{line}</div>)}</div></div></div></div></section> }

function Audience() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><Pill>Para quien decide</Pill><h2 className="mt-7 max-w-5xl text-[clamp(3.8rem,8vw,7.5rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Está diseñado<br />para quien toma decisiones.</h2><div className="mt-12 grid border-y border-black/10 sm:grid-cols-4">{['Dueños', 'Gerentes generales', 'Gerentes comerciales', 'Líderes de ventas'].map((person, i) => <div key={person} className="flex items-center gap-4 border-b border-black/10 py-5 sm:border-b-0 sm:border-r sm:px-5 sm:last:border-r-0"><span className="text-xl font-black text-[#FF4500]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>0{i + 1}</span><span className="text-sm font-bold uppercase" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{person}</span></div>)}</div><p className="mt-9 max-w-3xl text-lg leading-relaxed text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Especialmente relevante para empresas de distribución, importación, fabricación, representación de marcas, mayoristas y organizaciones con venta recurrente.</p></div></section> }

function NotCourse() { return <section className="bg-[#0A0A0A] px-4 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><h2 className="text-[clamp(3.5rem,8vw,7rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>No es un curso<br />de Power BI.<br /><span className="text-white/35">No es una clase<br />de Excel.</span></h2><p className="mt-9 text-4xl font-black uppercase text-[#FF4500] sm:text-6xl" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Es gestión comercial.</p><p className="mt-4 max-w-xl text-lg leading-relaxed text-white/65" style={{ fontFamily: 'var(--font-barlow)' }}>Una sesión ejecutiva para transformar datos en decisiones.</p></div></section> }

function FAQ() { return <section className="px-4 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-4xl"><Pill>Preguntas frecuentes</Pill><h2 className="mt-7 text-[clamp(4rem,9vw,8rem)] font-black uppercase leading-[0.8] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Antes de<br />reservar.</h2><div className="mt-12 divide-y divide-black/10 border-y border-black/10">{[['¿Tiene costo?', 'No.'], ['¿Cuánto dura?', '45 minutos aproximadamente.'], ['¿Necesito conocimientos técnicos?', 'No.'], ['¿Dónde se realizará?', 'Online. El acceso se enviará al correo registrado.']].map(([q, a]) => <details key={q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between text-xl font-black uppercase marker:hidden" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>{q}<span className="text-2xl text-[#FF4500] transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-base text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>{a}</p></details>)}</div></div></section> }

export function WebinarLanding() { return <div className="overflow-hidden bg-[#F5F1EA] text-[#0A0A0A]"><Header /><main><Hero /><ForYou /><Questions /><Takeaways /><BeforeAfter /><Example /><Audience /><NotCourse /><section id="registro-final" className="bg-[#0A0A0A] px-4 py-24 text-white sm:px-8 sm:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><div><Pill dark>03 sept · 20:00 hrs · online · 45 min · hora Chile</Pill><h2 className="mt-7 text-[clamp(4rem,9vw,8rem)] font-black uppercase leading-[0.78] tracking-[-0.05em]" style={{ fontFamily: 'var(--font-barlow-condensed)' }}>Reserva<br />tu cupo.</h2><p className="mt-6 max-w-sm text-lg leading-relaxed text-white/65" style={{ fontFamily: 'var(--font-barlow)' }}>Una sesión ejecutiva para transformar información en prioridades concretas.</p></div><WebinarRegistrationForm dark /></div></section><FAQ /><section className="px-4 pb-32 pt-10 text-center sm:px-8"><Logo /><p className="mx-auto mt-5 max-w-xl text-lg text-[#6f6963]" style={{ fontFamily: 'var(--font-barlow)' }}>Consultoría comercial, marketing y datos. Transformamos información en decisiones y decisiones en ejecución.</p><p className="mt-8 text-[10px] uppercase tracking-widest text-[#938b82]" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Taller Ejecutivo · 03 septiembre · 20:00 hrs · Online</p></section></main><a href="#registro" className="fixed bottom-4 left-4 right-4 z-40 flex min-h-12 items-center justify-center rounded-full bg-[#FF4500] px-6 text-xs font-bold uppercase tracking-widest text-white shadow-xl sm:hidden" style={{ fontFamily: 'var(--font-jetbrains-mono)' }}>Reservar cupo <ArrowRight className="ml-2 h-4 w-4" /></a></div> }
